configured_endpoints: 13
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stl-workshop-scale%2Fstl-workshop-scale-20241031-bc40feddc6546d5317d3aba9232d605c6c1a82ea91fae9457aed4d0478d429ab.yml
