configured_endpoints: 12
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stl-workshop-scale%2Fstl-workshop-scale-20241031-1215c663dc05a7ec48cd4a12dadb772a8b51c2c0bf886dfa19f772f513fb6c70.yml
